### ISSUE TITLE
UI is not launching

### ISSUE THREAD

**Issue by ramesharun** [YagelNasManit/environment.monitor#19]
Just tried your tutorial. After the Setup UI is not launching. 

I see the below error 
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu Nov 09 16:17:15 PST 2017
There was an unexpected error (type=Not Found, status=404).
No message available

**Comment by YagelNasManit** [comment]
Can you please provide steps you done so i can suggest a solution?

**Comment by ramesharun** [comment]
Thank you Yagel. I was just trying to use your Run-Test-Example steps. https://github.com/YagelNasManit/environment.monitor/wiki/Run-Test-Example

didn't see any errors in the server log. just that UI never lanches

**Comment by YagelNasManit** [comment]
Updated page to point to last artifacts, can you try once again, please? 
Seems that version 2.0.0 was uploaded without embedded UI, thanks for noticing, will fix it.

**Comment by ramesharun** [comment]
thanks that fixed the issue

**Comment by YagelNasManit** [comment]
Great, so i'll close issue. Please feel free to open new issues in case you'll have any further questions.
