### ISSUE TITLE
Environments and resources sorting

### ISSUE THREAD

**Issue by irynakov** [YagelNasManit/environment.monitor#9]
Environments and resources order should left same over the server restart.
Today it doesn't follow any sorting rule. 
I believe that environments and resources should be sorted by name by default.

**Comment by YagelNasManit** [comment]
That is the result of server side implementations of environment and resource statuses. 
Probably for user experience it worth to use sorting. 
Initially, plan for 3.0.0.
Community can propose solution

**Comment by irynakov** [comment]
I am willing to take this issue.

**Comment by YagelNasManit** [comment]
fixed with https://github.com/YagelNasManit/environment.monitor/pull/15
